### ISSUE TITLE
Allow user to login

### ISSUE THREAD

**Issue by seanauriti** [Emrals/EmTag#15]

**Comment by kartikarora** [comment]
@seanauriti Could you please explain the issue and what are you looking for?

**Comment by seanauriti** [comment]
@kartikarora we'd like the user to be able to login and when they tag a dirt alert, it will save it under their username at www.emrals.com there is login information at the previous app here - https://github.com/Emrals/Android

**Comment by kartikarora** [comment]
@seanauriti I'll have a look at it!

**Comment by seanauriti** [comment]
Thank you.

**Comment by kartikarora** [comment]
Do you have an api endpoint to login? and test credentials to go with that?

**Comment by seanauriti** [comment]
Yes, the endpoint is:

www.emrals.com/api/login/ - it's a POST
Variables are
username
password

Here is the Django Code for reference of what it will return:

@csrf_exempt
def login(request, authentication_form=AuthenticationForm):
    message= ""
    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            user_info = {}
            user_info["picture"] = request.user.profile_image_url()
            user_info["xp"] = request.user.xp()
            user_info["emrals"] = request.user.emrals()
            user_info["first_name"] = request.user.first_name
            return_val = json.dumps(user_info)
            return HttpResponse(return_val, mimetype='application/json')
            return HttpResponseRedirect(redirect_to)
        else:
            message = form.non_field_errors()
        
    return HttpResponse(message, mimetype='application/json')

You can signup for an account at www.emrals.com and use those credentials.

**Comment by kartikarora** [comment]
@seanauriti That's great. I'll send a PR soon!

**Comment by kartikarora** [comment]
@seanauriti Since I'll be testing the app, there might be some redundant posts on emrals. Could you delete them from your server later?

**Comment by seanauriti** [comment]
Yes, of course, thanks.

**Comment by kartikarora** [comment]
Hi @seanauriti. I've implemented the login and logout. Now the part left is to save a new dirt alert under the logged in user's username. Does the backend have provision for that?

**Comment by seanauriti** [comment]
Yes, it simply sends the username...you can check the existing code.

**Comment by kartikarora** [comment]
I see that `reqEntity` is taking a few parameters [here](https://github.com/Emrals/EmTag/blob/master/app/src/main/java/com/stickercamera/app/camera/ui/PhotoProcessActivity.java#L201)

Adding a `"username"` parameter should work right?

**Comment by seanauriti** [comment]
Oh, currently it uses Firstname and lastname... that should work.
Eventually we can change it to username and use a login token.

**Comment by seanauriti** [comment]
I've added last_name to the login endpoint

**Comment by kartikarora** [comment]
Thats great! Sending a PR in a few minutes!
