### ISSUE TITLE
Make the image work, currently it is uploading a black image

### ISSUE THREAD

**Issue by seanauriti** [Emrals/EmTag#19]

**Comment by NamanArora** [comment]
A screenshot would be helpful..

**Comment by seanauriti** [comment]
![screenshot_20161001-183537](https://cloud.githubusercontent.com/assets/7475382/19017400/f686c4a2-8805-11e6-83b9-5cff1b1614e5.png)

**Comment by seanauriti** [comment]
This is working now, however it's using the old code... I'll create a new issue for the update.
