### ISSUE TITLE
make back button go to main screen, not list

### ISSUE THREAD

**Issue by seanauriti** [Emrals/EmTag#7]

**Comment by mareiska** [comment]
When I tested, the back button on my android went to this.
![emtagback](https://cloud.githubusercontent.com/assets/16075543/18849329/834bbb5e-8400-11e6-9ac2-6ed1aad5e82b.png)

**Comment by twbarber** [comment]
Steps to reproduce?

**Comment by seanauriti** [comment]
This is the home screen... the app is supposed to open to the camera but when you go back this view was left over from the tweak... I have a solution for this in the works.

**Comment by seanauriti** [comment]
Feel free to fix it...

**Comment by seanauriti** [comment]
https://github.com/Emrals/EmTag/pull/17 was fixed by this
